import { locationTtfb, metricStatus } from '../../shared/metrics';
import type { HttpProbeRun, LocationResult, MetricStatus, RegionId, Report, TestLocation } from '../../shared/types';
import type { MarkerState } from '../components/WorldMap';

export interface LocationRow {
  location: TestLocation;
  result: LocationResult | null;
  ttfb: number | null;
  /** The run used for headline numbers: warm when available. */
  run: HttpProbeRun | null;
  state: MarkerState;
  statusLabel: string;
}

export function locationRows(report: Report): LocationRow[] {
  const byId = new Map((report.network?.locations ?? []).map((r) => [r.locationId, r]));
  return report.locations.map((location) => {
    const result = byId.get(location.id) ?? null;
    const ttfb = result ? locationTtfb(result) : null;
    const run = result ? (result.warm && !result.warm.error ? result.warm : result.cold) : null;
    let state: MarkerState = 'unselected';
    let statusLabel = 'Not measured';
    if (result?.status === 'failed' || result?.status === 'http-error') {
      state = 'failed';
      statusLabel = result.status === 'http-error' ? `HTTP ${run?.statusCode ?? 'error'}` : 'Failed';
    } else if (result?.status === 'no-probe') {
      statusLabel = 'No probe available';
    } else if (ttfb !== null) {
      state = metricStatus('ttfb', ttfb);
      statusLabel = state === 'good' ? 'Good' : state === 'poor' ? 'Poor' : 'Needs work';
    }
    return { location, result, ttfb, run, state, statusLabel };
  });
}

const FAST_TTFB = 300;

/** One-line plain-English verdict, e.g. "Fast in North America; moderate in Europe; slow in Oceania." */
export function deliveryVerdict(report: Report, regionLabels: Record<RegionId, string>): string | null {
  const regions = report.stats?.regions.filter((r) => r.status !== null && r.medianTtfb !== null) ?? [];
  if (regions.length === 0) return null;
  const names = (keep: (ms: number, status: MetricStatus | null) => boolean) =>
    regions.filter((r) => keep(r.medianTtfb as number, r.status)).map((r) => regionLabels[r.region]);
  const fast = names((ms) => ms <= FAST_TTFB);
  const moderate = names((ms, status) => ms > FAST_TTFB && status === 'good');
  const slow = names((_, status) => status !== 'good');
  const list = (items: string[]) =>
    items.length <= 2 ? items.join(' and ') : `${items.slice(0, -1).join(', ')} and ${items.at(-1)}`;

  const parts: string[] = [];
  if (fast.length === regions.length) parts.push('Fast first byte everywhere we tested');
  else {
    if (fast.length) parts.push(`fast in ${list(fast)}`);
    if (moderate.length) parts.push(`moderate in ${list(moderate)}`);
    if (slow.length) parts.push(`slow in ${list(slow)}`);
  }
  const failed = report.stats?.locationsFailed ?? 0;
  if (failed) parts.push(`${failed} location${failed > 1 ? 's' : ''} failed`);
  const sentence = parts.join('; ');
  return `${sentence.charAt(0).toUpperCase()}${sentence.slice(1)}.`;
}

export function severityCounts(report: Report): Record<'critical' | 'high' | 'medium' | 'low', number> {
  const counts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const r of report.recommendations) counts[r.severity]++;
  return counts;
}

export function worstStatus(statuses: Array<MetricStatus | null>): MetricStatus | null {
  if (statuses.includes('poor')) return 'poor';
  if (statuses.includes('needs-improvement')) return 'needs-improvement';
  return statuses.includes('good') ? 'good' : null;
}

/** Recommendations as a Markdown checklist, for pasting into an issue tracker. */
export function recommendationsMarkdown(report: Report): string {
  const lines = [
    `# Speed fixes for ${report.url}`,
    '',
    `Generated by Meridian on ${new Date(report.createdAt).toUTCString()}.`,
    '',
  ];
  report.recommendations.forEach((r, i) => {
    lines.push(`- [ ] **${i + 1}. [${r.severity.toUpperCase()}] ${r.title}** (${r.category})`);
    lines.push(`  ${r.summary}`);
    for (const fix of r.fixes) lines.push(`  - ${fix}`);
  });
  return lines.join('\n');
}
